### ISSUE TITLE
how did you build torchtext from source 

### ISSUE THREAD

**Issue by StephennFernandes** [bentrevett/pytorch-sentiment-analysis#97]
hey Great work on updating the torchtext code, 
sadly i tried to build torchtext from source as you instructed from the official repo. but i wasn't able to build from source. 
tried it on my linux machine, tried it on colab , kaggle notebooks , just couldn't make it work

**Comment by bentrevett** [comment]
Which errors are you getting?

I'll admit I haven't built a recent version of torchtext from source, but I do remember having significant issues with getting it to work in the past.

I definitely had to use PyTorch 1.7 as it wouldn't work on 1.6.

I will try to build from source later today and let you know if I'm able to.

**Comment by bentrevett** [comment]
@StephennFernandes

After a few attempts I wasn't able to build the master branch of torchtext. Please let me know if you figure out how.

**Comment by StephennFernandes** [comment]
@bentrevett 
the torchtext build from source is broken, it has compiling issues, you can try this nightly install. it works the same as build from source, as the nightly is build daily by torchtext folks. 

`!pip install --pre torchtext==0.9.0.dev20210212 -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html`

**Comment by StephennFernandes** [comment]
hey on that note could you show me a simple demo on how to use the `BPPTIterator` in pytorch for language modeling , i really gave it tons of try, but just coudn't figure it out

**Comment by DaddyALu** [comment]
> @bentrevett the torchtext build from source is broken, it has compiling issues, you can try this nightly install. it works the same as build from source, as the nightly is build daily by torchtext folks.
> 
> `!pip install --pre torchtext==0.9.0.dev20210212 -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html`

Hi, I have a problem as follow: 
`ModuleNotFoundError: No module named 'torchtext.legacy'`

Then I try to use
`!pip install --pre torchtext==0.9.0.dev20210212 -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html`
to solve it, and I got:
`ImportError: cannot import name 'unicode_csv_reader' from 'torchtext.utils' (/usr/local/lib/python3.7/dist-packages/torchtext/utils.py)`

Do you know how to deal with this issue?
Thank you!
